name: Docker

on:
  push:

  # Run tests for any PRs.
  pull_request:
       branches:
        - master
  
#  schedule:
#    - cron: "0 2 * * *"  
  workflow_dispatch:
    inputs:
      name:
        description: '备注'
        required: true
        default: 'Mona the Octocat'

  check_suite:
    types: [rerequested, completed]


jobs:
  push:
    runs-on: ubuntu-latest
#    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

#      - name: Build image
#        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64  #,linux/arm64,linux/arm/v7 暂不支持
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cq_eve_jita:latest